### ISSUE TITLE
Issue main.py

### ISSUE THREAD

**Issue by koff75** [f4T1H21/Wi-Phi#4]
Hi, thanks for this tool, very interesting !
I had follow your tutorial but I have an issue when starting : ampy run main.py
Maybe, I forgot something before...
```
C:\Users\xx\Downloads\Wi-Phi-main\Wi-Phi-main>ampy run main.py
[Wi-Fi] Wireless AP is active; ESSID = Google Free Wi-Fi, BSSID = 00:07:50:7F:84:3C
[DNS] Server listening on 210.210.210.1:53/udp
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Scripts\ampy.exe\__main__.py", line 7, in <module>
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ampy\cli.py", line 338, in run
    output = board_files.run(local_file, not no_output, not no_output)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ampy\files.py", line 309, in run
    self._pyboard.execfile(filename, stream_output=True)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ampy\pyboard.py", line 285, in execfile
    return self.exec_(pyfile, stream_output=stream_output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ampy\pyboard.py", line 279, in exec_
    raise PyboardError('exception', ret, ret_err)
ampy.pyboard.PyboardError: ('exception', b'[Wi-Fi] Wireless AP is active; ESSID = Google Free Wi-Fi, BSSID = 00:07:50:7F:84:3C\r\n[DNS] Server listening on 210.210.210.1:53/udp\r\n', b'Traceback (most recent call last):\r\n  File "<stdin>", line 58, in <module>\r\n  File "dns.py", line 65, in __init__\r\nAttributeError: \'UDPServer\' object has no attribute \'DNSServer\'\r\n')
```

**Comment by f4T1H21** [comment]
Hey Nicolas, thanks for your comment.

The source code of the tool is not shared at all. If someone just clone and try to run the software in this repository, lots of "something not found" errors will occur. The reason for me not to share all the source code is that this project could be easily converted to something that effects people badly. That's why think this behavior as a precaution.

You can learn about what I did and read the article about the operation principles of an advanced Wi-Fi Pineapple, but unfortunately I can't share the source code. Please take no offence, thank you for your understanding.

Kind regards,
Şefik Efe

**Comment by koff75** [comment]
Thanks for your reply :)

Kind regards,
Nicolas
